package cat.lsd.snpverify

// Regression cases: policy validation, input ownership, certificate purpose, CRL rules, masked CHIP_ID, VLEK. Mirrors ts/test/regression.test.ts.
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class RegressionTest {
    private fun fixture(name: String = "200-real-sev-snp-happy"): AppraisalInput {
        val x = Fixtures.json(Fixtures.vectors.resolve("attestation-sev/$name/input.json"))
        return AppraisalInput(
            evidence = Fixtures.gunzip(fromBase64(x["attestation_doc_b64"].asString)),
            endorsements = Endorsements(
                vcek = fromBase64(x["vcek_der_b64"].asString),
                ask = x["ask_pem"]?.let { pemToDer(it.asString)[0] },
                ark = x["amd_root_ca_pem"]?.let { pemToDer(it.asString)[0] },
            ),
            now = x["expiration_check_date_unix"]?.asLong ?: 1780272000L,
            policy = AppraisalPolicy(MeasurementPin.Any),
        )
    }
    private fun appraise(i: AppraisalInput): AppraisalResult = SnpVerifier(JcaCryptoProvider(), i.endorsements.ark?.let { listOf(it) }).appraise(i)
    private fun collateral(name: String) = Fixtures.vectors.resolve("review/$name").readBytes()
    private fun customChain() = fixture().with(ark = collateral("root.der"), ask = collateral("ask.der"), vcek = collateral("leaf.der"))

    @Test fun malformedLeafReturnsViolation() {
        val r = appraise(fixture().with(vcek = fromHex("300a3002a000300003020000"))) as AppraisalResult.Err
        assertEquals(ErrorCode.CERT_MALFORMED, r.violations[0].code)
    }

    @Test fun malformedCrlReturnsViolation() {
        val r = appraise(fixture().with(crl = fromHex("3006300030000300"))) as AppraisalResult.Err
        assertEquals(Stage.CHAIN, r.stage)
    }

    @Test fun negativeNumericPolicyIsRejected() {
        val r = appraise(fixture().with(policy = AppraisalPolicy(MeasurementPin.Any, minGuestSvn = -1, minReportVersion = -1, minTcb = mapOf(Product.Genoa to TcbFloor(snp = -1))))) as AppraisalResult.Err
        assertEquals(ErrorCode.POLICY_INVALID, r.violations[0].code)
    }

    @Test fun strongerEncryptionIsAcceptedByDefault() {
        val i = fixture("606-guest-policy-mem-aes256-xts")
        assertTrue(appraise(i) is AppraisalResult.Ok)
        val r = appraise(i.with(policy = i.policy.copy(guestPolicy = GuestPolicyRules(memAes256Xts = Bit.FORBIDDEN)))) as AppraisalResult.Err
        assertEquals("guest_policy.mem_aes_256_xts", r.violations[0].field)
    }

    @Test fun maskedChipIdIsSeparatelyRecognized() {
        // Vector 267 with MASK_CHIP_KEY cleared and re-signed (generated by the TypeScript review test); CHIP_ID is zero.
        val i = fixture("267-mask-chip-id-accept").with(evidence = collateral("masked-resigned.report"))
        assertTrue(appraise(i.with(policy = i.policy.copy(allowMaskedChipId = true))) is AppraisalResult.Ok)
        val r = appraise(i.with(policy = i.policy.copy(allowMaskedChipId = false))) as AppraisalResult.Err
        assertEquals(ErrorCode.POLICY_CHIP_ID_MASKED, r.violations[0].code)
    }

    @Test fun unknownCriticalCertificateExtensionIsRejected() {
        val r = appraise(customChain().with(vcek = collateral("unknown-critical-ext.der"))) as AppraisalResult.Err
        assertEquals(ErrorCode.CERT_MALFORMED, r.violations[0].code)
    }

    @Test fun nonCaIntermediateIsRejected() {
        val r = appraise(customChain().with(ask = collateral("non-ca.der"))) as AppraisalResult.Err
        assertEquals(ErrorCode.CERT_MALFORMED, r.violations[0].code)
    }

    @Test fun deltaCrlIsRejectedAsIncomplete() {
        val crl = collateral("delta.crl")
        val i = customChain()
        val r = appraise(i.with(crl = crl, now = parseCrl(crl).thisUpdate + 60, policy = i.policy.copy(requireCrl = true))) as AppraisalResult.Err
        assertEquals(ErrorCode.CRL_INVALID, r.violations[0].code)
    }

    @Test fun crlIssuerMustPermitCrlSigning() {
        val crl = collateral("valid.crl")
        val i = customChain().with(ark = collateral("root-no-crl-sign.der"), crl = crl, now = parseCrl(crl).thisUpdate + 60)
        val r = appraise(i) as AppraisalResult.Err
        assertEquals(ErrorCode.CRL_INVALID, r.violations[0].code)
    }

    @Test fun crlWithoutExpiryIsRejected() {
        val crl = collateral("no-expiry.crl")
        val i = customChain()
        assertEquals(null, parseCrl(crl).nextUpdate)
        val r = appraise(i.with(crl = crl, now = parseCrl(crl).thisUpdate + 365 * 86400, policy = i.policy.copy(requireCrl = true))) as AppraisalResult.Err
        assertEquals(ErrorCode.CRL_INVALID, r.violations[0].code)
    }

    @Test fun derStrictness() {
        // Malformed certificates derived from the ARK (generated by the TypeScript regression test); the message is the same in every port.
        for ((file, message) in listOf("empty-bit-string.der" to "DER: BIT STRING is empty", "empty-boolean.der" to "DER: extension critical flag must be one byte", "long-oid.der" to "DER: OID arc too large")) {
            val e = kotlin.test.assertFailsWith<Fail>(file) { parseCertificate(collateral(file)) }
            assertEquals(ErrorCode.CERT_MALFORMED to message, e.violation.code to e.violation.message, file)
        }
    }

    @Test fun vcekBasePolicyRequiresCrl() {
        val i = fixture()
        val crl = Fixtures.vectors.resolve("kds/Genoa.crl").readBytes()
        val policy = baseVcekAppraisalPolicy(
            BaseAppraisalPolicyConfig(
                products = listOf(Product.Genoa),
                measurements = listOf(i.evidence.copyOfRange(0x90, 0xc0)),
                reportData = i.evidence.copyOfRange(0x50, 0x90),
                minTcb = mapOf(Product.Genoa to TcbFloor(bootloader = 10, tee = 0, snp = 23, microcode = 84)),
            )
        )
        assertTrue(appraise(i.with(crl = crl, now = parseCrl(crl).thisUpdate + 60, policy = policy)) is AppraisalResult.Ok)
        val r = appraise(i.with(crl = null, now = parseCrl(crl).thisUpdate + 60, policy = policy)) as AppraisalResult.Err
        assertEquals(ErrorCode.POLICY_INVALID, r.violations[0].code)
    }

    @Test fun vlekBasePolicyRequiresCspId() {
        val config = BaseAppraisalPolicyConfig(listOf(Product.Genoa), listOf(ByteArray(48)), ByteArray(64) { 1 }, mapOf(Product.Genoa to TcbFloor(10, 0, 23, 84)))
        kotlin.test.assertFailsWith<IllegalArgumentException> { baseVlekAppraisalPolicy(config, emptyList()) }
        assertEquals(listOf("provider-1"), baseVlekAppraisalPolicy(config, listOf("provider-1")).cspIds)
    }

    @Test fun vlekBasePolicyChecksSignedCspId() {
        val report = collateral("vlek.report")
        val crl = collateral("vlek.crl")
        val input = AppraisalInput(
            report,
            Endorsements(collateral("vlek.der"), ask = collateral("asvk.der"), ark = collateral("vlek-root.der"), crl = crl),
            now = parseCrl(crl).thisUpdate + 60,
            policy = AppraisalPolicy(MeasurementPin.Any)
        )
        val config = BaseAppraisalPolicyConfig(listOf(Product.Genoa), listOf(report.copyOfRange(0x90, 0xc0)), report.copyOfRange(0x50, 0x90), mapOf(Product.Genoa to TcbFloor(10, 0, 23, 84)))
        assertTrue(appraise(input.with(policy = baseVlekAppraisalPolicy(config, listOf("provider-1")))) is AppraisalResult.Ok)
        val r = appraise(input.with(policy = baseVlekAppraisalPolicy(config, listOf("provider-2")))) as AppraisalResult.Err
        assertEquals(ErrorCode.POLICY_SIGNER_NOT_ALLOWED, r.violations[0].code)
    }
}
