//! Regression cases: policy validation, certificate purpose, CRL rules, masked CHIP_ID, VLEK. Mirrors ts/test/regression.test.ts.
//! Test endorsements and reports live in vectors/review, generated by the TypeScript regression test.

mod common;

use std::collections::BTreeMap;

use common::*;
use snpverify::*;

fn collateral(name: &str) -> Vec<u8> {
    read(&format!("review/{name}"))
}

fn custom_chain() -> AppraisalInput {
    let (i, _) = fixture("200-real-sev-snp-happy");
    AppraisalInput {
        endorsements: Endorsements {
            vcek: collateral("leaf.der"),
            ask: Some(collateral("ask.der")),
            ark: Some(collateral("root.der")),
            crl: None,
        },
        ..i
    }
}

fn genoa_floor() -> BTreeMap<Product, TcbFloor> {
    BTreeMap::from([(
        Product::Genoa,
        TcbFloor {
            bootloader: Some(10),
            tee: Some(0),
            snp: Some(23),
            microcode: Some(84),
            fmc: None,
        },
    )])
}

#[test]
fn malformed_leaf_returns_violation() {
    let (mut i, _) = fixture("200-real-sev-snp-happy");
    i.endorsements.vcek = from_hex("300a3002a000300003020000");
    assert_eq!(expect_err(appraise(&i), "leaf").violations[0].code, ErrorCode::CertMalformed);
}

#[test]
fn malformed_crl_returns_violation() {
    let (mut i, _) = fixture("200-real-sev-snp-happy");
    i.endorsements.crl = Some(from_hex("3006300030000300"));
    assert_eq!(expect_err(appraise(&i), "crl").stage, Stage::Chain);
}

#[test]
fn out_of_range_numeric_policy_is_rejected() {
    // The other ports pass negative values; Rust's unsigned types leave the range checks on min_report_version and vmpl.
    let (mut i, _) = fixture("200-real-sev-snp-happy");
    i.policy = AppraisalPolicy {
        min_report_version: Some(1),
        ..AppraisalPolicy::new(MeasurementPin::Any)
    };
    assert_eq!(expect_err(appraise(&i), "version").violations[0].code, ErrorCode::PolicyInvalid);
    i.policy = AppraisalPolicy {
        vmpl: Some(4),
        ..AppraisalPolicy::new(MeasurementPin::Any)
    };
    assert_eq!(expect_err(appraise(&i), "vmpl").violations[0].code, ErrorCode::PolicyInvalid);
}

#[test]
fn stronger_encryption_is_accepted_by_default() {
    let (mut i, _) = fixture("606-guest-policy-mem-aes256-xts");
    assert!(appraise(&i).is_ok());
    i.policy.guest_policy = Some(GuestPolicyRules {
        mem_aes256_xts: Some(Bit::Forbidden),
        ..Default::default()
    });
    assert_eq!(expect_err(appraise(&i), "aes").violations[0].field.as_deref(), Some("guest_policy.mem_aes_256_xts"));
}

#[test]
fn masked_chip_id_is_separately_recognized() {
    // Vector 267 with MASK_CHIP_KEY cleared and re-signed (generated by the TypeScript regression test); CHIP_ID is zero.
    let (mut i, _) = fixture("267-mask-chip-id-accept");
    i.evidence = collateral("masked-resigned.report");
    i.policy.allow_masked_chip_id = Some(true);
    assert!(appraise(&i).is_ok());
    i.policy.allow_masked_chip_id = Some(false);
    assert_eq!(expect_err(appraise(&i), "masked").violations[0].code, ErrorCode::PolicyChipIdMasked);
}

#[test]
fn unknown_critical_certificate_extension_is_rejected() {
    let mut i = custom_chain();
    i.endorsements.vcek = collateral("unknown-critical-ext.der");
    assert_eq!(expect_err(appraise(&i), "ext").violations[0].code, ErrorCode::CertMalformed);
}

#[test]
fn non_ca_intermediate_is_rejected() {
    let mut i = custom_chain();
    i.endorsements.ask = Some(collateral("non-ca.der"));
    assert_eq!(expect_err(appraise(&i), "nonca").violations[0].code, ErrorCode::CertMalformed);
}

#[test]
fn delta_crl_is_rejected_as_incomplete() {
    let crl = collateral("delta.crl");
    let mut i = custom_chain();
    i.now = this_update(&crl) + 60;
    i.endorsements.crl = Some(crl);
    i.policy.require_crl = Some(true);
    assert_eq!(expect_err(appraise(&i), "delta").violations[0].code, ErrorCode::CrlInvalid);
}

#[test]
fn crl_issuer_must_permit_crl_signing() {
    let crl = collateral("valid.crl");
    let mut i = custom_chain();
    i.now = this_update(&crl) + 60;
    i.endorsements.ark = Some(collateral("root-no-crl-sign.der"));
    i.endorsements.crl = Some(crl);
    assert_eq!(expect_err(appraise(&i), "crlsign").violations[0].code, ErrorCode::CrlInvalid);
}

#[test]
fn crl_without_expiry_is_rejected() {
    let crl = collateral("no-expiry.crl");
    assert_eq!(parse_crl(&crl).unwrap().next_update, None);
    let mut i = custom_chain();
    i.now = this_update(&crl) + 365 * 86400;
    i.endorsements.crl = Some(crl);
    i.policy.require_crl = Some(true);
    assert_eq!(expect_err(appraise(&i), "noexpiry").violations[0].code, ErrorCode::CrlInvalid);
}

#[test]
fn vcek_base_policy_requires_crl() {
    let (mut i, _) = fixture("200-real-sev-snp-happy");
    let crl = read("kds/Genoa.crl");
    let policy = base_vcek_appraisal_policy(&BaseAppraisalPolicyConfig {
        products: vec![Product::Genoa],
        measurements: vec![i.evidence[0x90..0xc0].to_vec()],
        report_data: i.evidence[0x50..0x90].to_vec(),
        min_tcb: genoa_floor(),
    })
    .unwrap();
    i.now = this_update(&crl) + 60;
    i.endorsements.crl = Some(crl);
    i.policy = policy;
    assert!(appraise(&i).is_ok());
    i.endorsements.crl = None;
    assert_eq!(expect_err(appraise(&i), "nocrl").violations[0].code, ErrorCode::PolicyInvalid);
}

#[test]
fn vlek_base_policy_requires_csp_id() {
    let config = BaseAppraisalPolicyConfig {
        products: vec![Product::Genoa],
        measurements: vec![vec![0; 48]],
        report_data: vec![1; 64],
        min_tcb: genoa_floor(),
    };
    assert!(base_vlek_appraisal_policy(&config, &[]).is_err());
    let p = base_vlek_appraisal_policy(&config, &["provider-1".to_string()]).unwrap();
    assert_eq!(p.csp_ids, Some(vec!["provider-1".to_string()]));
    assert_eq!(p.signing_key, Some(SigningKeyPolicy::Vlek));
}

#[test]
fn vlek_base_policy_checks_signed_csp_id() {
    let (report, crl) = (collateral("vlek.report"), collateral("vlek.crl"));
    let mut input = AppraisalInput {
        evidence: report.clone(),
        endorsements: Endorsements {
            vcek: collateral("vlek.der"),
            ask: Some(collateral("asvk.der")),
            ark: Some(collateral("vlek-root.der")),
            crl: Some(crl.clone()),
        },
        now: this_update(&crl) + 60,
        policy: AppraisalPolicy::new(MeasurementPin::Any),
    };
    let config = BaseAppraisalPolicyConfig {
        products: vec![Product::Genoa],
        measurements: vec![report[0x90..0xc0].to_vec()],
        report_data: report[0x50..0x90].to_vec(),
        min_tcb: genoa_floor(),
    };
    input.policy = base_vlek_appraisal_policy(&config, &["provider-1".to_string()]).unwrap();
    assert!(appraise(&input).is_ok());
    input.policy = base_vlek_appraisal_policy(&config, &["provider-2".to_string()]).unwrap();
    assert_eq!(expect_err(appraise(&input), "csp").violations[0].code, ErrorCode::PolicySignerNotAllowed);
}

#[test]
fn der_strictness() {
    // Malformed certificates derived from the ARK (generated by the TypeScript regression test); the message is the same in every port.
    for (file, message) in [
        ("empty-bit-string.der", "DER: BIT STRING is empty"),
        ("empty-boolean.der", "DER: extension critical flag must be one byte"),
        ("long-oid.der", "DER: OID arc too large"),
    ] {
        let e = parse_certificate(&collateral(file)).err().unwrap_or_else(|| panic!("{file}: expected CERT_MALFORMED"));
        assert_eq!((e.code, e.message.as_str()), (ErrorCode::CertMalformed, message), "{file}");
    }
}
