package snpverify

// Regression cases: policy validation, input ownership, certificate purpose, CRL rules, masked CHIP_ID, VLEK. Mirrors ts/test/regression.test.ts.
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class RegressionTest {
    private fun fixture(name: String = "200-real-sev-snp-happy"): VerifyInput {
        val x = Fixtures.json(Fixtures.vectors.resolve("attestation-sev/$name/input.json"))
        return VerifyInput(
            report = Fixtures.gunzip(fromBase64(x["attestation_doc_b64"].asString)),
            vcek = fromBase64(x["vcek_der_b64"].asString),
            ask = x["ask_pem"]?.let { pemToDer(it.asString)[0] },
            ark = x["amd_root_ca_pem"]?.let { pemToDer(it.asString)[0] },
            now = x["expiration_check_date_unix"]?.asLong ?: 1780272000L,
            policy = Policy(MeasurementPin.Any),
        )
    }
    private fun verify(i: VerifyInput): VerifyResult = SnpVerifier(JcaCryptoProvider(), i.ark?.let { listOf(it) }).verify(i)
    private fun collateral(name: String) = Fixtures.vectors.resolve("review/$name").readBytes()
    private fun customChain() = fixture().copy(ark = collateral("root.der"), ask = collateral("ask.der"), vcek = collateral("leaf.der"))

    @Test fun malformedLeafReturnsViolation() {
        val r = verify(fixture().copy(vcek = fromHex("300a3002a000300003020000"))) as VerifyResult.Err
        assertEquals(ErrorCode.CERT_MALFORMED, r.violations[0].code)
    }

    @Test fun malformedCrlReturnsViolation() {
        val r = verify(fixture().copy(crl = fromHex("3006300030000300"))) as VerifyResult.Err
        assertEquals(Stage.CHAIN, r.stage)
    }

    @Test fun negativeNumericPolicyIsRejected() {
        val r = verify(fixture().copy(policy = Policy(MeasurementPin.Any, minGuestSvn = -1, minReportVersion = -1, minTcb = mapOf(Product.Genoa to TcbFloor(snp = -1))))) as VerifyResult.Err
        assertEquals(ErrorCode.POLICY_INVALID, r.violations[0].code)
    }

    @Test fun strongerEncryptionIsAcceptedByDefault() {
        val i = fixture("606-guest-policy-mem-aes256-xts")
        assertTrue(verify(i) is VerifyResult.Ok)
        val r = verify(i.copy(policy = i.policy.copy(guestPolicy = GuestPolicyRules(memAes256Xts = Bit.FORBIDDEN)))) as VerifyResult.Err
        assertEquals("guest_policy.mem_aes_256_xts", r.violations[0].field)
    }

    @Test fun maskedChipIdIsSeparatelyRecognized() {
        // Vector 267 with MASK_CHIP_KEY cleared and re-signed (generated by the TypeScript review test); CHIP_ID is zero.
        val i = fixture("267-mask-chip-id-accept").copy(report = collateral("masked-resigned.report"))
        assertTrue(verify(i.copy(policy = i.policy.copy(allowMaskedChipId = true))) is VerifyResult.Ok)
        val r = verify(i.copy(policy = i.policy.copy(allowMaskedChipId = false))) as VerifyResult.Err
        assertEquals(ErrorCode.POLICY_CHIP_ID_MASKED, r.violations[0].code)
    }

    @Test fun unknownCriticalCertificateExtensionIsRejected() {
        val r = verify(customChain().copy(vcek = collateral("unknown-critical-ext.der"))) as VerifyResult.Err
        assertEquals(ErrorCode.CERT_MALFORMED, r.violations[0].code)
    }

    @Test fun nonCaIntermediateIsRejected() {
        val r = verify(customChain().copy(ask = collateral("non-ca.der"))) as VerifyResult.Err
        assertEquals(ErrorCode.CERT_MALFORMED, r.violations[0].code)
    }

    @Test fun deltaCrlIsRejectedAsIncomplete() {
        val crl = collateral("delta.crl")
        val i = customChain()
        val r = verify(i.copy(crl = crl, now = parseCrl(crl).thisUpdate + 60, policy = i.policy.copy(requireCrl = true))) as VerifyResult.Err
        assertEquals(ErrorCode.CRL_INVALID, r.violations[0].code)
    }

    @Test fun crlIssuerMustPermitCrlSigning() {
        val crl = collateral("valid.crl")
        val i = customChain().copy(ark = collateral("root-no-crl-sign.der"), crl = crl, now = parseCrl(crl).thisUpdate + 60)
        val r = verify(i) as VerifyResult.Err
        assertEquals(ErrorCode.CRL_INVALID, r.violations[0].code)
    }

    @Test fun crlWithoutExpiryIsRejected() {
        val crl = collateral("no-expiry.crl")
        val i = customChain()
        assertEquals(null, parseCrl(crl).nextUpdate)
        val r = verify(i.copy(crl = crl, now = parseCrl(crl).thisUpdate + 365 * 86400, policy = i.policy.copy(requireCrl = true))) as VerifyResult.Err
        assertEquals(ErrorCode.CRL_INVALID, r.violations[0].code)
    }

    @Test fun vcekBasePolicyRequiresCrl() {
        val i = fixture()
        val crl = Fixtures.vectors.resolve("kds/Genoa.crl").readBytes()
        val policy = baseVcekPolicy(
            BasePolicyConfig(
                products = listOf(Product.Genoa),
                measurements = listOf(i.report.copyOfRange(0x90, 0xc0)),
                reportData = i.report.copyOfRange(0x50, 0x90),
                minTcb = mapOf(Product.Genoa to TcbFloor(bootloader = 10, tee = 0, snp = 23, microcode = 84)),
            )
        )
        assertTrue(verify(i.copy(crl = crl, now = parseCrl(crl).thisUpdate + 60, policy = policy)) is VerifyResult.Ok)
        val r = verify(i.copy(crl = null, now = parseCrl(crl).thisUpdate + 60, policy = policy)) as VerifyResult.Err
        assertEquals(ErrorCode.POLICY_INVALID, r.violations[0].code)
    }

    @Test fun vlekBasePolicyRequiresCspId() {
        val config = BasePolicyConfig(listOf(Product.Genoa), listOf(ByteArray(48)), ByteArray(64) { 1 }, mapOf(Product.Genoa to TcbFloor(10, 0, 23, 84)))
        kotlin.test.assertFailsWith<IllegalArgumentException> { baseVlekPolicy(config, emptyList()) }
        assertEquals(listOf("provider-1"), baseVlekPolicy(config, listOf("provider-1")).cspIds)
    }

    @Test fun vlekBasePolicyChecksSignedCspId() {
        val report = collateral("vlek.report")
        val crl = collateral("vlek.crl")
        val input = VerifyInput(
            report,
            collateral("vlek.der"),
            ask = collateral("asvk.der"),
            ark = collateral("vlek-root.der"),
            crl = crl,
            now = parseCrl(crl).thisUpdate + 60,
            policy = Policy(MeasurementPin.Any)
        )
        val config = BasePolicyConfig(listOf(Product.Genoa), listOf(report.copyOfRange(0x90, 0xc0)), report.copyOfRange(0x50, 0x90), mapOf(Product.Genoa to TcbFloor(10, 0, 23, 84)))
        assertTrue(verify(input.copy(policy = baseVlekPolicy(config, listOf("provider-1")))) is VerifyResult.Ok)
        val r = verify(input.copy(policy = baseVlekPolicy(config, listOf("provider-2")))) as VerifyResult.Err
        assertEquals(ErrorCode.POLICY_SIGNER_NOT_ALLOWED, r.violations[0].code)
    }
}
