package snpverify_test

// Regression cases: policy validation, certificate purpose, CRL rules, masked CHIP_ID, VLEK. Mirrors ts/test/regression.test.ts.
// Test endorsements and reports live in vectors/review, generated by the TypeScript regression test.

import (
	"bytes"
	"errors"
	"testing"

	snp "github.com/lsd-cat/snpverify/go"
)

func appraise(t *testing.T, i snp.AppraisalInput) (*snp.AttestationResult, error) {
	t.Helper()
	return verifierFor(i).Appraise(i)
}

func appraiseFail(t *testing.T, i snp.AppraisalInput) *snp.AppraisalError {
	t.Helper()
	_, err := appraise(t, i)
	return mustFail(t, err, "expected rejection")
}

func collateral(t *testing.T, name string) []byte { return readFile(t, "review/"+name) }

func customChain(t *testing.T) snp.AppraisalInput {
	i, _ := fixture(t, "200-real-sev-snp-happy")
	i.Endorsements = snp.Endorsements{VCEK: collateral(t, "leaf.der"), ASK: collateral(t, "ask.der"), ARK: collateral(t, "root.der")}
	return i
}

func TestMalformedLeafReturnsViolation(t *testing.T) {
	i, _ := fixture(t, "200-real-sev-snp-happy")
	i.Endorsements.VCEK = fromHex(t, "300a3002a000300003020000")
	if e := appraiseFail(t, i); e.Violations[0].Code != snp.CertMalformed {
		t.Fatal(e.Violations)
	}
}

func TestMalformedCrlReturnsViolation(t *testing.T) {
	i, _ := fixture(t, "200-real-sev-snp-happy")
	i.Endorsements.CRL = fromHex(t, "3006300030000300")
	if e := appraiseFail(t, i); e.Stage != snp.StageChain {
		t.Fatal(e.Stage)
	}
}

func TestNegativeNumericPolicyIsRejected(t *testing.T) {
	i, _ := fixture(t, "200-real-sev-snp-happy")
	i.Policy = snp.AppraisalPolicy{Measurement: snp.MeasurementAny{}, MinGuestSVN: -1, MinReportVersion: -1, MinTCB: map[snp.Product]snp.TCBFloor{snp.Genoa: {SNP: new(-1)}}}
	if e := appraiseFail(t, i); e.Violations[0].Code != snp.PolicyInvalid {
		t.Fatal(e.Violations)
	}
}

func TestStrongerEncryptionIsAcceptedByDefault(t *testing.T) {
	i, _ := fixture(t, "606-guest-policy-mem-aes256-xts")
	if _, err := appraise(t, i); err != nil {
		t.Fatal(err)
	}
	i.Policy.GuestPolicy = snp.GuestPolicyRules{MemAES256XTS: snp.BitForbidden}
	if e := appraiseFail(t, i); e.Violations[0].Field != "guest_policy.mem_aes_256_xts" {
		t.Fatal(e.Violations)
	}
}

func TestMaskedChipIdIsSeparatelyRecognized(t *testing.T) {
	// Vector 267 with MASK_CHIP_KEY cleared and re-signed (generated by the TypeScript regression test); CHIP_ID is zero.
	i, _ := fixture(t, "267-mask-chip-id-accept")
	i.Evidence = collateral(t, "masked-resigned.report")
	i.Policy.AllowMaskedChipID = true
	if _, err := appraise(t, i); err != nil {
		t.Fatal(err)
	}
	i.Policy.AllowMaskedChipID = false
	if e := appraiseFail(t, i); e.Violations[0].Code != snp.PolicyChipIDMasked {
		t.Fatal(e.Violations)
	}
}

func TestUnknownCriticalCertificateExtensionIsRejected(t *testing.T) {
	i := customChain(t)
	i.Endorsements.VCEK = collateral(t, "unknown-critical-ext.der")
	if e := appraiseFail(t, i); e.Violations[0].Code != snp.CertMalformed {
		t.Fatal(e.Violations)
	}
}

func TestNonCaIntermediateIsRejected(t *testing.T) {
	i := customChain(t)
	i.Endorsements.ASK = collateral(t, "non-ca.der")
	if e := appraiseFail(t, i); e.Violations[0].Code != snp.CertMalformed {
		t.Fatal(e.Violations)
	}
}

func TestDeltaCrlIsRejectedAsIncomplete(t *testing.T) {
	crl := collateral(t, "delta.crl")
	i := customChain(t)
	i.Endorsements.CRL, i.Now, i.Policy.RequireCRL = crl, thisUpdate(t, crl)+60, true
	if e := appraiseFail(t, i); e.Violations[0].Code != snp.CRLInvalid {
		t.Fatal(e.Violations)
	}
}

func TestCrlIssuerMustPermitCrlSigning(t *testing.T) {
	crl := collateral(t, "valid.crl")
	i := customChain(t)
	i.Endorsements.ARK, i.Endorsements.CRL, i.Now = collateral(t, "root-no-crl-sign.der"), crl, thisUpdate(t, crl)+60
	if e := appraiseFail(t, i); e.Violations[0].Code != snp.CRLInvalid {
		t.Fatal(e.Violations)
	}
}

func TestCrlWithoutExpiryIsRejected(t *testing.T) {
	crl := collateral(t, "no-expiry.crl")
	parsed, err := snp.ParseCRL(crl)
	if err != nil || parsed.NextUpdate != nil {
		t.Fatal("expected a CRL without nextUpdate")
	}
	i := customChain(t)
	i.Endorsements.CRL, i.Now, i.Policy.RequireCRL = crl, parsed.ThisUpdate+365*86400, true
	if e := appraiseFail(t, i); e.Violations[0].Code != snp.CRLInvalid {
		t.Fatal(e.Violations)
	}
}

func TestVcekBasePolicyRequiresCrl(t *testing.T) {
	i, _ := fixture(t, "200-real-sev-snp-happy")
	crl := readFile(t, "kds/Genoa.crl")
	policy, err := snp.BaseVCEKAppraisalPolicy(snp.BaseAppraisalPolicyConfig{
		Products:     []snp.Product{snp.Genoa},
		Measurements: [][]byte{i.Evidence[0x90:0xc0]},
		ReportData:   i.Evidence[0x50:0x90],
		MinTCB:       map[snp.Product]snp.TCBFloor{snp.Genoa: {Bootloader: new(10), TEE: new(0), SNP: new(23), Microcode: new(84)}},
	})
	if err != nil {
		t.Fatal(err)
	}
	i.Endorsements.CRL, i.Now, i.Policy = crl, thisUpdate(t, crl)+60, policy
	if _, err := appraise(t, i); err != nil {
		t.Fatal(err)
	}
	i.Endorsements.CRL = nil
	if e := appraiseFail(t, i); e.Violations[0].Code != snp.PolicyInvalid {
		t.Fatal(e.Violations)
	}
}

func TestVlekBasePolicyRequiresCspId(t *testing.T) {
	config := snp.BaseAppraisalPolicyConfig{Products: []snp.Product{snp.Genoa}, Measurements: [][]byte{make([]byte, 48)}, ReportData: bytes.Repeat([]byte{1}, 64),
		MinTCB: map[snp.Product]snp.TCBFloor{snp.Genoa: {Bootloader: new(10), TEE: new(0), SNP: new(23), Microcode: new(84)}}}
	if _, err := snp.BaseVLEKAppraisalPolicy(config, nil); err == nil {
		t.Fatal("expected an error without CSP_IDs")
	}
	p, err := snp.BaseVLEKAppraisalPolicy(config, []string{"provider-1"})
	if err != nil || len(p.CSPIDs) != 1 || p.CSPIDs[0] != "provider-1" || p.SigningKey != snp.SigningKeyPolicyVLEK {
		t.Fatalf("%+v %v", p, err)
	}
}

func TestVlekBasePolicyChecksSignedCspId(t *testing.T) {
	report, crl := collateral(t, "vlek.report"), collateral(t, "vlek.crl")
	input := snp.AppraisalInput{
		Evidence:     report,
		Endorsements: snp.Endorsements{VCEK: collateral(t, "vlek.der"), ASK: collateral(t, "asvk.der"), ARK: collateral(t, "vlek-root.der"), CRL: crl},
		Now:          thisUpdate(t, crl) + 60,
	}
	config := snp.BaseAppraisalPolicyConfig{Products: []snp.Product{snp.Genoa}, Measurements: [][]byte{report[0x90:0xc0]}, ReportData: report[0x50:0x90],
		MinTCB: map[snp.Product]snp.TCBFloor{snp.Genoa: {Bootloader: new(10), TEE: new(0), SNP: new(23), Microcode: new(84)}}}
	policy, err := snp.BaseVLEKAppraisalPolicy(config, []string{"provider-1"})
	if err != nil {
		t.Fatal(err)
	}
	input.Policy = policy
	if _, err := appraise(t, input); err != nil {
		t.Fatal(err)
	}
	input.Policy, _ = snp.BaseVLEKAppraisalPolicy(config, []string{"provider-2"})
	if e := appraiseFail(t, input); e.Violations[0].Code != snp.PolicySignerNotAllowed {
		t.Fatal(e.Violations)
	}
}

func TestDerStrictness(t *testing.T) {
	// Malformed certificates derived from the ARK (generated by the TypeScript regression test); the message is the same in every port.
	for file, message := range map[string]string{
		"empty-bit-string.der": "DER: BIT STRING is empty",
		"empty-boolean.der":    "DER: extension critical flag must be one byte",
		"long-oid.der":         "DER: OID arc too large",
	} {
		_, err := snp.ParseCertificate(collateral(t, file))
		var v *snp.Violation
		if !errors.As(err, &v) || v.Code != snp.CertMalformed || v.Message != message {
			t.Fatalf("%s: want CERT_MALFORMED %q, got %v", file, message, err)
		}
	}
}
